### ISSUE TITLE
Adding servers to serverlist without permission of the owner.

### ISSUE THREAD

**Issue by red-001** [minetest/master-server#12]
You can add servers to the serverlist just by setting `server_address` to their IP address or domain name and starting a server.

**Comment by sfan5** [comment]
This check was disabled by me to avoid problems if servers announce over IPv6 but don't have a domain or don't have an AAAA record in their domain.

**Comment by ShadowNinja** [comment]
FWIW, I announce over IPv6 and accept both IPv6 and IPv4 traffic on one of my servers.  I think this is what all IPv6-capable servers should be doing.
