### ISSUE TITLE
Update apt-get listing to latest

### ISSUE THREAD

**Issue by krainboltgreene** [minetest/master-server#18]
It's currently resting at 0.4.13.

**Comment by sfan5** [comment]
What?

**Comment by krainboltgreene** [comment]
The current debian release of minetest-server is 0.4.13, but the latest release is 0.4.16.

**Comment by sfan5** [comment]
1) This is not in our control.
2) Debian is known for providing "stable" (outdated) software, I'm sure they are aware.
3) The repository for the Minetest website is here: [minetest/minetest.github.io](https://github.com/minetest/minetest.github.io)
