### ISSUE TITLE
Increase maximum points for player count

### ISSUE THREAD

**Issue by Lejo1** [minetest/master-server#26]
The limit lays at 16 points and the limit for the average players at 4 points.
The Minetest community has grown a lot so today are there much servers with more than 16 players.
I prefer to double both limits to 32 and 8 points.

What do you think?
[Forum Topic](https://forum.minetest.net/viewtopic.php?f=10&t=20776)

**Comment by sfan5** [comment]
And which advantage do you perceive in this change for the sorting of the serverlist?

**Comment by Lejo1** [comment]
In the moment there are much servers with the maximum points.
So they should all be at the first place but they can’t.
This will just sort this first place servers so that really the best server is at the top.

**Comment by nerzhul** [comment]
with 5.0.0 it's easy to have 20 players without lag, if you have just a baremetal mtg it should run with 40 players without lag

**Comment by Lejo1** [comment]
Yes!
And that’s the reason why the maximum points for the players should be higher.

**Comment by sofar** [comment]
I don't think raising the number of points is fair. 

With the unrealistic high limit set at 200, I don't think this is needed at all.

**Comment by Minetest-One** [comment]
So, for the last weeks "Blocky Survival" has shown often enough 40+ gamer and as I have been playing there for 5 days, building a base, farming, mine ... above 40 it is getting lag.
Ok that depends on also installed mods and hardware, but
* as the list has some reasons (age, trust sorting) famous (gamer points)
I see no reason 100 was chosen, as before was 16 (what was proofed is working at some servers), and 32 was sure possible (and proofed by Blocky Survival also),
but on my opinion, a maximum of 50 is until now enough as no server can proof handling that gamer without getting to trouble.
So set 50 or maybe 60 is enough, as so the listed server automatic sort better, when a "full" server looses points, let other a chance
(a bit of haha, after looking that these days) - don't complain me, I have 5.0 server and don't take any gamers away - 3 days 3 logins ... nobody games 5.0 yet. But my tests show other things ...

**Comment by Lejo1** [comment]
The last change(Tune server ranking) did this changes(except the average points.
So I’m fine with no more changes.
