### ISSUE TITLE
Maybe disallow forks being listed on the server list?

### ISSUE THREAD

**Issue by Linuxdirk** [minetest/master-server#32]
Recently in the forums a discussion started whether to allow forks being listed in the server list or not allow forks being listed.

https://forum.minetest.net/viewtopic.php?p=349681#p349681 ff.
https://forum.minetest.net/viewtopic.php?f=3&t=22745

It should be clarified if 3rd party applications that were forked from any of the Minetest releases should be allowed on the official Minetest server list or if there should be usage guidelines or technical solutions to prevent forks being listed.

Cons:

* Forks "steal" players from other servers because most of them are more popular than Minetest, especially on mobile
* Forks are not Minetest, but it is the Minetest server list
* Forks are not Minetest, but players expect Minetest and not some altered somewhat compatible other software based on Minetest
* There could be licensing issues with the forks
* Preconfiguring and hosting an own serverlist server is easy and forks can and should do that

Pros:

* They centralize (most) mobile gamers on their own servers and mobile gamers are not that much liked by some Minetest server hosters.
* Do nothing because a fork can simply announce itself as normal Minetest server anyways

**Comment by nerzhul** [comment]
you will only make them being rogue inside the server list

**Comment by sfan5** [comment]
Allowing forks to use the server list (provided they <i>behave</i>) is very much in the spirit of FOSS.
Disallowing forks in general would unnecessarily fragment the Minetest player base while bringing few advantages. Besides, the majority of forks (or variants) don't do anything we would consider undesirable.

**Comment by SmallJoker** [comment]
This is an open-source project, so expect forks. As long they're legal I don't see any issue with allowing those in the server list. Strictly spoken: testing servers with custom patches aren't much different, except that they keep the project name in their version string. :-1:

**Comment by rubenwardy** [comment]
:-1: for reasons given above.

If servers are found to be misbehaving, then they will be dealt with individually.

**Comment by appgurueu** [comment]
Probably add a flag ?
