### ISSUE TITLE
Table alternate colours for rows (tr tags)

### ISSUE THREAD

**Issue by za267** [minetest/master-server#36]
In style.css I would recommend having a nth-child tr configured so that we can have alternating colours per row.  This would make it easier to scan the row's data further away on the right hand side.

A code example:

```
#server_list tr:nth-child(odd) {
	background: #grey;
}
#server_list tr:nth-child(even) {
	background: #white;
}
```

**Comment by sfan5** [comment]
The CSS already did this but the coloring was a little too subtle.
fixed in ddcd98a457b6d4d147d89a372fff123d7096014f
