### ISSUE TITLE
No uniquness by connection address

### ISSUE THREAD

**Issue by neoascetic** [minetest/master-server#8]
It is possible now to have several servers with same ip/domain name and port in the list.
For example, at this moment you may see two Krondor servers: one is mine, and second belongs to someone else. Both are registered with krondor.neoascetic.me as domain name.

**Comment by PilzAdam** [comment]
Which list?

**Comment by ShadowNinja** [comment]
The server diferentiates by IP and port and checks that the IP is listed in DNS.  If the domain you mentioned is a round robin address pointing to both servers this would be valid.  It probably shouldn't be allowed though, since the client might chose the other address.

**Comment by neoascetic** [comment]
My domain has the only IP address associated with it. So it seems like something is broken.

**Comment by ShadowNinja** [comment]
Here's the relevant (simplified) code.  It seems to be correct.
```Python
info = socket.getaddrinfo(server["address"],
	server["port"],
	type=socket.SOCK_DGRAM,
	proto=socket.SOL_UDP)

addresses = set(data[4][0] for data in info)
if not server["ip"] in addresses:
	return
```

**Comment by neoascetic** [comment]
Please check it yourself. There are two servers in the list with the same name, while domain points to single IP:

```
❯ host krondor.neoascetic.me
krondor.neoascetic.me has address 52.28.96.56
```

I cannot see real server's IP in the list.

**Comment by sfan5** [comment]
@ShadowNinja @neoascetic Sorry for not responding earlier.

Actually I commented this check out, it was causing problems with ipv4 servers announcing over ipv6.
This isn't much of a problem thought, the only thing you can do (which you wouldn't be able to normally)  is announcing other peoples servers.

**Comment by ShadowNinja** [comment]
@sfan5: Well *that* would explain it!  If a server decides to go IPv4-only they should probably announce over IPv4 too.

**Comment by sfan5** [comment]
Yeah, that's the problem. To make sure you announce over IPv4 you need to set some httpfetch bindaddress something setting in minetest.conf to your public IP. Nobody does that, it would be better if MT had an on-by-default settings that forces announcing over IPv4. (server admins can then set it to false if they want IPv6).

**Comment by ShadowNinja** [comment]
Well, this isn't actually an issue with the master server but with a modified version, which is due to a Minetest bug, so I'll close this.
Minetest issue: minetest/minetest#3609
